AWSTemplateFormatVersion: 2010-09-09
Description: ALB resources
Resources:
  BastionHost:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0ff21806645c5e492
      KeyName: !Ref BastionKeyPair
      SubnetId: !ImportValue PracticePublicSubnet1
      UserData:
        Fn::Base64: |
              #!/bin/bash
              sudo yum localinstall https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm -y
              sudo rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
              sudo yum install -y mysql-community-client
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
  BastionIPAddress:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
      InstanceId: !Ref BastionHost
  BastionSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable access to the Bastion host
      VpcId: !ImportValue PracticeVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 3.112.23.0/29 # https://ip-ranges.amazonaws.com/ip-ranges.json
  BastionKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: BastionKeyPair
Outputs:
  Bastion:
    Description: IP Address of the Bastion host
    Value: !Ref BastionIPAddress
